version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network-between-db-and-spring-boot

  spaces-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network-between-db-and-spring-boot

networks:
  my-network-between-db-and-spring-boot:
    driver: bridge

volumes:
  pgdata: